### ISSUE TITLE
Issues building on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by macsforme** [jamesturton/rr64x#1]
First of all, thank you so much for maintaining this.  It's a big help to be able to use my RAID card on a modern Linux distro.

I am by no means an expert on kernel modules, but I was able to work around the build issues I found by using some workarounds I found online.  I do not know whether these are *proper* fixes, but I hope they serve as a starting point.

I tried compiling with both the standard kernel (5.4.0-42-generic) and also the HWE kernel (5.8.0-55-generic).  In either case, compilation fails:

<details>
<summary>5.4.0-42-generic kernel error</summary>

    DKMS make.log for rr64x-1.1x for kernel 5.4.0-42-generic (x86_64)
    Thu 03 Jun 2021 06:59:54 PM MST
    make: Entering directory '/var/lib/dkms/rr64x/1.1x/build/product/rr64x/linux'
    make[1]: Entering directory '/usr/src/linux-headers-5.4.0-42-generic'
      DESCEND  objtool
    /usr/src/linux-headers-5.4.0-42-generic/tools/build/Makefile.build:37: /usr/src/linux-headers-5.4.0-42-generic/tools/build/Build.include: No such file or directory
    make[5]: *** No rule to make target '/usr/src/linux-headers-5.4.0-42-generic/tools/build/Build.include'.  Stop.
    make[4]: *** [Makefile:43: /usr/src/linux-headers-5.4.0-42-generic/tools/objtool/fixdep-in.o] Error 2
    make[3]: *** [/usr/src/linux-headers-5.4.0-42-generic/tools/build/Makefile.include:5: fixdep] Error 2
    make[2]: *** [Makefile:67: objtool] Error 2
    make[1]: *** [Makefile:1835: tools/objtool] Error 2
    make[1]: *** Waiting for unfinished jobs....
    make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-42-generic'
    make: *** [../../../inc/linux/Makefile.def:108: rr64x.ko] Error 2
    make: Leaving directory '/var/lib/dkms/rr64x/1.1x/build/product/rr64x/linux'
</details>

<details>
<summary>5.8.0-55-generic kernel error</summary>

    DKMS make.log for rr64x-1.1x for kernel 5.8.0-55-generic (x86_64)
    Thu 03 Jun 2021 07:05:10 PM MST
    make: Entering directory '/var/lib/dkms/rr64x/1.1x/build/product/rr64x/linux'
    make[1]: Entering directory '/usr/src/linux-headers-5.8.0-55-generic'
      DESCEND  objtool
    make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
    make[1]: *** [arch/x86/Makefile:214: archscripts] Error 2
    make[1]: *** Waiting for unfinished jobs....
    /usr/src/linux-headers-5.8.0-55-generic/tools/build/Makefile.build:37: /usr/src/linux-headers-5.8.0-55-generic/tools/build/Build.include: No such file or directory
    make[5]: *** No rule to make target '/usr/src/linux-headers-5.8.0-55-generic/tools/build/Build.include'.  Stop.
    make[4]: *** [Makefile:39: /usr/src/linux-headers-5.8.0-55-generic/tools/objtool/fixdep-in.o] Error 2
    make[3]: *** [/usr/src/linux-headers-5.8.0-55-generic/tools/build/Makefile.include:5: fixdep] Error 2
    make[2]: *** [Makefile:68: objtool] Error 2
    make[1]: *** [Makefile:1887: tools/objtool] Error 2
    make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-55-generic'
    make: *** [../../../inc/linux/Makefile.def:108: rr64x.ko] Error 2
    make: Leaving directory '/var/lib/dkms/rr64x/1.1x/build/product/rr64x/linux'
</details>

Most of the internet search results for this error suggested that `M=$(PWD)` needs to be changed to `M=$(shell pwd)`.  I found no instances of the former code.  However, I ultimately found that this change corrects this particular issue:

<details>
<summary>Patch</summary>

    diff --git a/inc/linux/Makefile.def b/inc/linux/Makefile.def
    index 9e24f9e..124b40e 100755
    --- a/inc/linux/Makefile.def
    +++ b/inc/linux/Makefile.def
    @@ -105,7 +105,7 @@ ifneq ($(KERNEL_VER), 2.4)
     TARGET := $(TARGETNAME).ko
     
     $(TARGETNAME).ko: $(CURDIR)/.build/Makefile
    -	@$(MAKE) -C $(KERNELDIR) SUBDIRS=$(CURDIR)/.build modules
    +	@$(MAKE) -C $(KERNELDIR) M=$(CURDIR)/.build modules
     	@cp -f $(CURDIR)/.build/$(TARGETNAME).ko $(CURDIR)/
     
     .PHONY: $(CURDIR)/.build/Makefile
</details>

With this change, the module builds successfully on the 5.4.0-42-generic kernel.  When building on the 5.8.0-55-generic kernel, there is an additional error:

<details>
<summary>5.8.0-55-generic kernel error</summary>

    make[1]: Entering directory '/usr/src/linux-headers-5.8.0-55-generic'
      CC [M]  /usr/src/rr64x-1.1x/product/rr64x/linux/.build/os_linux.o
      CC [M]  /usr/src/rr64x-1.1x/product/rr64x/linux/.build/osm_linux.o
    /usr/src/rr64x-1.1x/product/rr64x/linux/.build/osm_linux.c:2191:45: warning: missing braces around initializer [-Wmissing-braces]
     2191 | static Scsi_Host_Template driver_template = {
          |                                             ^
      CC [M]  /usr/src/rr64x-1.1x/product/rr64x/linux/.build/div64.o
      CC [M]  /usr/src/rr64x-1.1x/product/rr64x/linux/.build/hptinfo.o
      CC [M]  /usr/src/rr64x-1.1x/product/rr64x/linux/.build/config.o
      LD [M]  /usr/src/rr64x-1.1x/product/rr64x/linux/.build/rr64x.o
      MODPOST /usr/src/rr64x-1.1x/product/rr64x/linux/.build/Module.symvers
    /usr/src/rr64x-1.1x/product/rr64x/linux/.build/.him_magni.o.cmd: No such file or directory
    make[2]: *** [scripts/Makefile.modpost:111: /usr/src/rr64x-1.1x/product/rr64x/linux/.build/Module.symvers] Error 1
    make[1]: *** [Makefile:1698: modules] Error 2
    make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-55-generic'
    make: *** [../../../inc/linux/Makefile.def:108: rr64x.ko] Error 2
</details>

The problem seems to lie with the line ending with `No such file or directory`.  If I simply `touch` all of the .cmd files it's looking for, then the build succeeds; e.g., `sudo touch /usr/src/rr64x-1.1x/product/rr64x/linux/.build/.him_magni.o.cmd` (for each occurrence of this error):

    cd /usr/src/rr64x-1.1x/product/rr64x/linux/.build
    sudo touch .him_magni.o.cmd .ldm_raid.o.cmd .partition.o.cmd .raid0.o.cmd .raid1.o.cmd .raid5.o.cmd .jbod.o.cmd

However, I'm not sure of how to implement that kind of workaround in the make system, or whether there may be a better solution.  In any case, this allowed me to build and use the module.  Thanks so much for your work on this!

**Comment by jamesturton** [comment]
Hi @macsforme!
Thanks for taking the time to fix these build errors! Much appreciated!
You are right, It seems that from kernel 5.3 support for `SUBDIRS` has been dropped in favor of `M`.
I have also modified the Makefile to touch the `.cmd` files which are now apparently required in kernel 5.8.

Please let me know if you have any more issues and I'll see if I can help!
